Transform access to Rule/Root
RadValentin/postcss-prefix-selector pull request #109
Opened 2022-06-15 17:08 UTC by luttje

In issue #108 we discussed getting access to the raw postcss Root in the transform callback. While I was working on this I realized that you can get Root from a Rule (Rule#root). Giving the user access to the current Rule therefor opens up even more options.

I have added tests that also demonstrate why this feature is useful.

If you don't mind making a breaking change I would consider removing this line: https://github.com/luttje/postcss-prefix-selector/blob/c61250e46d63f34913702253f076de72a0daa730/index.js#L47 Since that can now be reached through `rule.root.source.input.file`

Let me know if I need to add/change something. If you think it's all good, let me know and I'll add a bit of explanation to the README as well.

2022-06-16 11:52 UTC, RadValentin requested changes
Looks good, left one comment. Let's not introduce any breaking changes in this PR, instead I'll make a note to look at dropping `root.source.input.file` as part of PostCSS 8 upgrade #95 . Feel free to update the readme to mention the new `rule` argument.

2022-06-16 13:16 UTC, luttje commented on test/fixtures/transform.css
> +/* no-prefix-for:.class-ignored-by-root */
Good point! I will try find time today to extract these to their own tests.

I'll also make a note in the readme.

2022-06-16 15:49 UTC, luttje commented
@RadValentin Separated tests and added a bit to README. Let me know if I can do anything else here.

2022-06-17 10:59 UTC, RadValentin approved these changes
Looks good!

2022-06-17 10:59 UTC, merged

2022-06-17 11:16 UTC, RadValentin commented
Published v1.16.0 which includes the changes in this PR, thanks for contributing!

2022-06-17 13:57 UTC, luttje commented
My pleasure! 👍