Add new options includeFiles and bethSymbol
RadValentin/postcss-prefix-selector pull request #87
Opened 2021-03-09 20:21 UTC by MaximusFT

I hope all my changes will be clear.
Add tests for all new cases. All test is green
![image](https://user-images.githubusercontent.com/587509/110532412-11f16700-811d-11eb-8e5c-7cdfca3b650f.png)

Feel free to write in any question.

- minor refactor
- add option.includeFiles
- add option.bethSymbol
- add tests to cover new features
- update Readme

PS: for me important to use an updated version in my project )

2021-03-09 20:22 UTC, MaximusFT commented
These changes can close #77 issue.

2021-03-10 14:28 UTC, RadValentin commented
I'm not sure I understand how `bethSymbol` is supposed to be used. To get this result `.hello+.a`, which is the same as `.hello + .a` you could just set the existing prefix param to: `prefix: '.hello +'`. AFAIK CSS doesn't care if there are spaces or not.

For gluing the prefix to the selector (`.hello.a`), the transform param can be used:

```
transform(prefix, selector, prefixedSelector) {
  return prefix + selector;
}
```

Since both the cases you presented are already covered by existing functionality then I'd avoid adding more params to the plugin.

2021-03-10 14:32 UTC, RadValentin commented on index.js
> +  const searchSelector = (selector, searchArray) => {
I'd like to keep this as a separate function

2021-03-10 14:33 UTC, RadValentin requested changes
I'd remove `bethSelector` since it's covered by existing functionality.

2021-03-10 16:47 UTC, MaximusFT commented
> > These changes can help to close #77 issue.
> 
> That issue was referring to prefixing only certain selectors, not certain files so sadly it will remain open :(

Yes, you right... I didn't pay enough attention

2021-03-10 16:48 UTC, MaximusFT commented
Update PR.
Leave new tests and solve them as you propose.

2021-03-11 11:22 UTC, RadValentin requested changes
PR looks better but you need to solve the issue I mentioned with how includeFiles works and update the tests.

2021-03-11 11:22 UTC, RadValentin commented on index.js
> +      includeFiles.some((file) => !root.source.input.file.includes(file))
This won't work as expected, if the `includeFiles` array has two entries for example 'a.css' and `b.css` this will return `false`.

2021-03-11 11:22 UTC, RadValentin commented on test/test.js
> +it('should prefix selectors in included file', () => {
Please add tests for empty include array and include array with multiple files

2021-03-11 11:22 UTC, RadValentin commented on test/test.js
> +it('should use custom symbol between prefix and selector. Use "+"', () => {
Please remove this test, I don't see the value of having it anymore.

2021-03-11 21:25 UTC, MaximusFT commented
@RadValentin 
Thanks for the review.
Update PR

2021-03-12 09:52 UTC, RadValentin commented
Looks good to me! 👍  Thanks for contributing, I'll release a new version of the plugin today.

2021-03-12 09:52 UTC, merged